### ISSUE TITLE
KingWorld path

### ISSUE THREAD

**Issue by yusukebe** [SaltyAom/bun-http-framework-benchmark#11]
Hi!

This line seems to be incorrect:
https://github.com/SaltyAom/bun-http-framework-benchmark/blob/9eb0a9aea6ef4bc9473a05e4abdd57f32657391c/package.json#L23

Thank you!

**Comment by SaltyAom** [comment]
My bad, I was testing something on my local and forgot to change it back.
For transparency, I re-installed the published package and re-run the benchmark again.
Thanks for informing!
