### ISSUE TITLE
Add Fastify to benchmark

### ISSUE THREAD

**Issue by themre** [SaltyAom/bun-http-framework-benchmark#12]
Would be nice to see also https://www.fastify.io/ in the benchmarks.

**Comment by SaltyAom** [comment]
We have [fastify](https://github.com/SaltyAom/bun-http-framework-benchmark/blob/a2827c0c1184e31de0ee77ee43b3aaa16c9c1e6e/src/fastify.ts) but it doesn't work with Bun yet.

It might be an unfair comparison for frameworks on different runtimes but we can do it.

**Comment by themre** [comment]
Ah nice to hear, thanks! You can close the issue due to this fact or leave it if there will be some time to add support for bun.
