### ISSUE TITLE
Elysia 

### ISSUE THREAD

**Issue by aquapi** [SaltyAom/bun-http-framework-benchmark#17]
![image](https://user-images.githubusercontent.com/87530663/217888825-de241d6e-f65a-4348-bba9-d3d07ecc0118.png)
Elysia may returns only the text or JSON without the header in the test so it is faster than the Bun and Stric implementation.

**Comment by SaltyAom** [comment]
As stated in test (3):
> Post JSON
> [POST] /json
> Mirror body to response
> For the benchmark, the request body will be sent as: { "hello": "world" }
> Expected response: { "hello": "world" }

It's expected that the response should contain a `Content-Type: application/json` header to indicate whether the response is JSON or not.

Elysia automatically appends headers `Content-Type: application/json` by default, therefore, it's not need to set one in the user code.
<img width="912" alt="Screenshot 2566-02-10 at 13 37 52" src="https://user-images.githubusercontent.com/35027979/218020338-435c5a45-9186-4df2-87e6-39d4ebe9854c.png">

To test if it actually is, you can run:
```bash
bun src/elysia.ts
```

Then use the REST client to see the response's headers, there should be a `Content-Type: application/json`.

You may see [the code in current version of Elysia that it automatically map the response header if the response is JSON](https://github.com/elysiajs/elysia/blob/51070e6247ed780534908df06138ed55f2da65d6/src/handler.ts#L122)

<img width="723" alt="Screenshot 2566-02-10 at 13 43 36" src="https://user-images.githubusercontent.com/35027979/218021332-98d46f7b-7307-4152-83ea-d0e541e42cb9.png">
