### ISSUE TITLE
bun-bakery is not working

### ISSUE THREAD

**Issue by yusukebe** [SaltyAom/bun-http-framework-benchmark#38]
Hi,

bun-bakery is not working correctly now.

<img width="387" alt="Screenshot 2023-07-30 at 7 04 11" src="https://github.com/SaltyAom/bun-http-framework-benchmark/assets/10682/31c2da9d-6eed-4f6d-a18a-d0d0a6764c97">

<img width="663" alt="Screenshot 2023-07-30 at 7 04 01" src="https://github.com/SaltyAom/bun-http-framework-benchmark/assets/10682/6ca9484c-7777-4a1b-bab4-ac9d671c39de">

You can ignore it from the benchmark.

**Comment by SaltyAom** [comment]
Hi, thanks for the report.
I've removed Bun Bakery from the benchmark, thanks a lot!
