### ISSUE TITLE
Why is the uws benchmark run only under Node.js and not Bun also?

### ISSUE THREAD

**Issue by murraybauer** [SaltyAom/bun-http-framework-benchmark#49]
With the "uws framework (node)" entry always being the top performer, why is it only ever run under Node.js and not re-run under Bun also?

I understand uws is used as the built-in web server of Bun and then also ElysiaJS.  But there's no vanilla standalone benchmark run for it using Bun? Is it not possible?

**Comment by aquapi** [comment]
@murraybauer it is uws.js
uws.js is based on V8 headers, which is not available in Bun

**Comment by murraybauer** [comment]
Thanks @aquapi !

**Comment by murraybauer** [comment]
Closing

**Comment by melroy89** [comment]
I would like to point out one more thing.. UWS shouldn't be used anymore, instead you should use: uWebSockets, right? https://github.com/uNetworking/uWebSockets.js
