### ISSUE TITLE
Easiest way to run a single library?

### ISSUE THREAD

**Issue by ImLunaHey** [SaltyAom/bun-http-framework-benchmark#52]
Trying to get my own library added to this and I'm stuck re-running the whole benchmark each time with all of the other libraries.

Is there a way around this? I feel this there's something super obvious that I've missed. 😓

**Comment by aquapi** [comment]
@ImLunaHey https://github.com/bunsvr/benchmark
I have this benchmark
For my benchmark you can go to `config.ts` and add an `include` option which accepts a list of frameworks to include

**Comment by SaltyAom** [comment]
Edit the `framework` array to only include your framework prefers.

https://github.com/SaltyAom/bun-http-framework-benchmark/blob/fbc33d0f170e837aab6d2a6277b4619d62e0ec4f/bench.mjs#L77
