### ISSUE TITLE
More complex tests

### ISSUE THREAD

**Issue by aquapi** [SaltyAom/bun-http-framework-benchmark#66]
Maybe write a TODO app for each framework with some authentications.
See how hard it is to write a simple TODO app and compare the performance (signup/login API and rendering)

**Comment by aquapi** [comment]
Would be good if you can split dependencies instead of putting all of them in a single `package.json` file.

**Comment by Shyam-Chen** [comment]
> https://github.com/Vanilla-IceCream/fastify-uws?tab=readme-ov-file#benchmarks

I have separated each library into its own `package.json` file.
