### ISSUE TITLE
uWS.DeclarativeResponse is an option

### ISSUE THREAD

**Issue by uNetworkingAB** [SaltyAom/bun-http-framework-benchmark#74]
This variant: https://github.com/uNetworking/uWebSockets.js/blob/master/examples/Benchmarker.cjs

should be about 2x the perf. for the first 2 tests. You could possibly add another test case called "uws with declarative response" or such. Would be interesting to see what results you get from that. I get about 2x.

Requires latest version.

**Comment by SaltyAom** [comment]
Update with [9cc1f98](https://github.com/SaltyAom/bun-http-framework-benchmark/commit/9cc1f98a6bb53b26018ef390aeb9e40264d4b4d3), thanks for your contribution
